# Generated by Django 3.0 on 2020-10-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_remove_wheel_isdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='img',
            field=models.CharField(max_length=350),
        ),
    ]
