# Generated by Django 3.0 on 2020-10-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0003_auto_20201003_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=10)),
                ('trackid', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='wheel',
            name='img',
            field=models.CharField(max_length=150),
        ),
    ]
