# Generated by Django 3.0 on 2020-10-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20)),
                ('productid', models.CharField(max_length=20)),
                ('productnum', models.CharField(max_length=20)),
                ('productprice', models.CharField(max_length=20)),
                ('isChose', models.IntegerField(default=False)),
                ('productimg', models.CharField(max_length=20)),
                ('productname', models.CharField(max_length=20)),
                ('orderid', models.CharField(default=0, max_length=20)),
                ('isDelete', models.IntegerField(default=False)),
            ],
        ),
    ]
